Automobile Sensor
Manish-Fexle-May2022/Manish_May_2022 pull request #28
Opened 2022-08-09 17:59 UTC by Manish-Fexle-May2022

Assignment Automobile sensor

2022-08-12 20:30 UTC, shubhamsharmafexletraining requested changes

2022-08-12 20:30 UTC, shubhamsharmafexletraining commented on src/classes/OpportunityHelper.cls
> +                    tableRow = tableRow + '<tr><td>Presence Sensor</td><td>'+recAutomobile.Name+'</td><td>Presence Sensor inserted under installation account : '+recAutomobile.Account__r.Name+'</td><
Break lines

2022-08-17 07:07 UTC, Manish-Fexle-May2022 commented on src/classes/OpportunityHelper.cls
> +    public static Automobile_Sensor__c recordSensor(Boolean isAfter,List<String> NameList){
Sir I am Using Boolean isAfter for Not Creating Duplicate Records when Updating Opportunity stage

2022-08-19 17:48 UTC, shubhamsharmafexletraining commented on src/classes/OpportunityHelper.cls
> +    public static Automobile_Sensor__c recordSensor(Boolean isAfter,List<String> NameList){
This is not the correct logic. You are passing trigger.isUpdate to the helper class method and on update you are not creating/updating any sensor. This is the wrong approach. sensors records should be create/update/delete when opportunity create/Update and having the appropriate stage. this whole logic is wrong.

2022-08-19 17:49 UTC, shubhamsharmafexletraining commented
Closing the pull request for wrong logic. please raise another pull request with correct logic.

2022-08-21 17:50 UTC, closed without merging